src/WebApplication1/Program.cs
src/WebApplication1/Startup.cs
src/WebApplication3/Program.cs
src/WebApplication3/Startup.cs

Added namespace changes for RestApi and TicketShop

Changed namespace for WebAPI in RestAPI and TicketShop

---

src/WebApplication3/wwwroot/css/site.css

small change with the Ticketshop view

small change with the Ticketshop view

---

src/WebApplication3/Controllers/HomeController.cs

Just added explicitly which view file we are returning for the actions we have defined in homecontroller in TicketShop.sln, probobly need to add which model we are using in most of the actions methods too, later on

Minor adjustment to homecontroller action methods

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/ValuesController.cs

Fixed method GetSpecificEvent in restapi so it returns a specific eve…nt in json-format. Fixed method 'SpecificEventFind' in ticketdatabase class so we return one event from the TicketEvent table in the database.

Fixed get-method in rest api and method in ticketdatabase to get one specific event from database

---

src/WebApplication3/Controllers/HomeController.cs
src/WebApplication3/TicketShopWebapp.csproj
src/WebApplication3/Views/Home/Login.cshtml
src/WebApplication3/Views/Home/Register.cshtml
src/WebApplication3/wwwroot/css/site.css

Added Register button and view

Added Register button and view

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs

Added method for creating a new event in the databse to TicketDatabas…eclass, started on put-method for this in restapi.

Added method for creating new event in the database

---

src/TicketShopWeb/Views/Account/Login.cshtml
src/TicketShopWeb/Views/Home/Index.cshtml
src/TicketShopWeb/wwwroot/css/site.css

ticketshop stuff

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/CustomerAdministrationController.cs
src/WebApplication1/Controllers/TicketTransactionController.cs
src/WebApplication1/Controllers/VenueController.cs

removed GET = Name from several controllers as it caused errors.

Link to database established within venue get all method. 

---

src/TicketShopWeb/Views/Account/Register.cshtml
src/TicketShopWeb/wwwroot/css/site.css

fixed manage login site

---

src/TicketShopWeb/Views/Home/Index.cshtml
src/TicketShopWeb/wwwroot/css/site.css

Started with ticket page, not done!

Started with ticket page, not done!

---

src/TicketShopWeb/wwwroot/css/site.css

small fix css

---

src/TicketShopWeb/Views/Home/Index.cshtml
src/TicketShopWeb/wwwroot/css/site.css

small fixes

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs

Edited method for creating new event in TicketDatabase class, now parameterized, created method in TicketDatabase class for updating existing event. Created corresponding method in RestAPI class to update event, edited method for creating event (post).

Edited methods in TicketDatabase class, edited methods in RestAPI class (EventController)

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs

Created delete method in ticketdatabase class, implemented 'delete' method in restapi class eventcontroller

Delete event method ticketdatabase class, delete method added in restapi class eventcontroller

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs
src/WebApplication1/Controllers/VenueController.cs

Parameterized method UpdateVenue in TicketDatabase class. Changed Put method in VenueController class so it matches method in EventController class, added error response if venue id is not found in database. Added Venufind method in TicketDatabaseclass, to find a specific venue.

Made some changes to TicketDatabase methods and methods in VenueController class

---

src/DatabaseRepository/ITicketDatabase.cs
src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs
src/WebApplication1/Controllers/VenueController.cs

Fixed rest of methods in Venuecontroller and corresponding database methods in Ticketdatabase class.

Methods added in venuecontroller for delete as well as finding specific venue vs. get a list of a lot of venues matching search criteria

---

src/TicketShopWeb/Views/Home/Index.cshtml
src/TicketShopWeb/Views/Shared/_Layout.cshtml
src/TicketShopWeb/wwwroot/css/site.css

some new design and other stuff

some new design and other stuff

---

src/TicketShopWeb/Controllers/HomeController.cs
src/TicketShopWeb/Views/Home/Cart.cshtml
src/TicketShopWeb/Views/Home/Index.cshtml
src/TicketShopWeb/Views/Shared/_Layout.cshtml
src/TicketShopWeb/wwwroot/css/site.css

small fixes and added cart view

small fixes and added cart view

---

.gitignore
src/DatabaseRepository/Model/Order.cs
src/DatabaseRepository/Model/TicketToTransaction.cs
src/DatabaseRepository/TicketDatabase.cs
src/RestApi.sln

Added a new model class: Order, to represent the case when a ticket administrator wants to get information about a customer order from the database. Started with this database method- not finished yet.

New class in restapi model: order

---

src/DatabaseRepository/TicketDatabase.cs
src/WebApplication1/Controllers/EventController.cs
src/WebApplication1/Controllers/TicketEventDateController.cs

Added methods to Ticketdatabase class to handle administration of TicketEventDates (connection between venues and tickevents), added methods in restapi class TicketEventDateController that can be used to administer this

Added methods for administration of ticketeventdates

---

src/WebApplication1/Controllers/EventController.cs
src/WebApplication1/Controllers/OrderAdministrationController.cs
src/WebApplication1/Controllers/TicketEventDateController.cs
src/WebApplication1/Controllers/VenueController.cs

Address for api becomes localhost:port/api/controller
Example: http://localhost:51775/api/Venue

Fixed routing in REST api controllers.

---

src/BackofficeWeb/Controllers/HomeController.cs
src/BackofficeWeb/Views/Home/Index.cshtml
src/RestApiClient/VenueApi.cs

razor in html to populate gui with venues from database

FUSION! it works.

---

src/TicketShopWeb/Resources/Views.Home.Index.en-US.resx
src/TicketShopWeb/Resources/Views.Home.Index.sv-SE.resx
src/TicketShopWeb/Startup.cs
src/TicketShopWeb/TicketShopWeb.csproj

some stuff for language

---

src/BackofficeWeb/BackofficeWeb.csproj
src/BackofficeWeb/Resources/Views.Home.Contact.en.resx
src/BackofficeWeb/Resources/Views.Home.Contact.sv.resx
src/BackofficeWeb/Startup.cs
src/BackofficeWeb/Views/Home/Contact.cshtml

languages added in backoffice

---

src/BackofficeWeb/Views/Home/VenueAdd.cshtml
src/DatabaseRepositoryTestclient/Program.cs

removed old commented out script, fixed test some

VenueAdd title label change,

---

src/BackofficeWeb/Views/Home/Orders.cshtml

html for Orders

---

src/BackofficeWeb/Controllers/HomeController.cs
src/BackofficeWeb/Views/Home/Orders.cshtml

Order site fix

---

src/DatabaseRepository/TicketDatabase.cs
src/TicketSystemEngine/Order.cs
src/WebApplication1/Controllers/OrderController.cs

Changed database methods for orders, since they need to contain more than one ticket if customer wants to buy several tickets we can't have eventname and eventdate in these methods. Instead we just work with the information int TicketTransaction database table. Also made corresponding changes in Order class. Added a check in CreateOrder method in OrderController that checks if paymentstatus was 'approved', if not- the order is not created.
To get information on the Event to the view where customers see their order as well as where administrators see customer order you need to now use methods that gets the Ticket objects instead (for information on datetime, eventname, etc.).

Change in order class and change of order-related methods in Ticketdatabase class

---

src/BackofficeWeb/Views/Home/Orders.cshtml

fix Orderhtml

---

src/TicketShopWeb/Controllers/HomeController.cs
src/TicketShopWeb/Resources/Views.Account.Login.sv.resx
src/TicketShopWeb/Resources/Views.Account.Register.sv.resx
src/TicketShopWeb/Resources/Views.Home.About.sv.resx
src/TicketShopWeb/Resources/Views.Shared._Layout.sv.resx
src/TicketShopWeb/Resources/Views.Shared._LoginPartial.sv.resx
src/TicketShopWeb/TicketShopWeb.csproj
src/TicketShopWeb/Views/Account/Login.cshtml
src/TicketShopWeb/Views/Account/Register.cshtml
src/TicketShopWeb/Views/Home/About.cshtml
src/TicketShopWeb/Views/Shared/_Layout.cshtml
src/TicketShopWeb/Views/Shared/_LoginPartial.cshtml

translate done in ticketshop

---

src/BackofficeWeb/BackofficeWeb.csproj
src/BackofficeWeb/Controllers/HomeController.cs
src/BackofficeWeb/Resources/Views.Account.Login.sv.resx
src/BackofficeWeb/Resources/Views.Home.About.sv.resx
src/BackofficeWeb/Resources/Views.Home.Venues.sv.resx
src/BackofficeWeb/Views/Account/Login.cshtml
src/BackofficeWeb/Views/Home/About.cshtml
src/BackofficeWeb/Views/Home/Contact.cshtml
src/BackofficeWeb/Views/Home/Venues.cshtml

translations done @ backoffice

translations done @ backoffice

---

src/DatabaseRepository/DatabaseRepository.csproj
src/PaymentProvider/PaymentProvider.csproj
src/TicketSystemEngine/TicketSystemEngine.csproj
src/WebApplication1/RESTapi.csproj
src/WebApplication1/Startup.cs

If you dont get nuget package from this:
right click restapi solution, pick manage nuget packages for this solution and get Seq.Extensions.Logging

first steps in adding Logging.

---

src/TicketShopWeb/Views/Home/Cart.cshtml

cart design done

---

src/TicketShopWeb/Views/Home/Cart.cshtml

Added delete button and other small fixes in Cart view

Added delete button and other small fixes in Cart view

---

src/TicketShopWeb/Resources/Views.Home.Index.sv.resx
src/TicketShopWeb/Views/Home/Index.cshtml

added translations @ index ticketshop

added translations @ index ticketshop

---

src/BackofficeWeb/BackofficeWeb.csproj
src/BackofficeWeb/Resources/Views.Home.DateAdd.sv.resx
src/BackofficeWeb/Resources/Views.Home.EditEvent.sv.resx
src/BackofficeWeb/Resources/Views.Home.Events.sv.resx
src/BackofficeWeb/Resources/Views.Home.Order.sv.resx
src/BackofficeWeb/Views/Home/DateAdd.cshtml
src/BackofficeWeb/Views/Home/EditEvent.cshtml
src/BackofficeWeb/Views/Home/Events.cshtml
src/BackofficeWeb/Views/Home/Order.cshtml
src/BackofficeWeb/Views/Shared/_Layout.cshtml

translations finish @ backoffice

translations finish @ backoffice

---

src/TicketShopWeb/Views/Home/Index.cshtml

small fix with footer in Index View

small fix with footer in Index View

---

src/TicketShopWeb/Controllers/HomeController.cs
src/TicketShopWeb/Resources/Views.Home.OrderAdd.sv.resx
src/TicketShopWeb/TicketShopWeb.csproj
src/TicketShopWeb/Views/Home/OrderAdd.cshtml

Added OrderAdd view + translations and stuff @ ticketshop

Added OrderAdd view + translations and stuff @ ticketshop
